services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - tour_data:/var/lib/postgresql/data
    networks:
      - tour_network

  app:
    image: ${APP_IMAGE}
    depends_on:
      - postgres
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
      - .env
    networks:
      - tour_network



volumes:
  tour_data:

networks:
  tour_network:
    driver: bridge