services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - tour_data:/var/lib/postgresql/data

volumes:
  tour_data:
